In [3]:
import sys, os

In [4]:
from common_utils.utils import chunks
from tqdm import tqdm
from matplotlib import pyplot as plt
from pylab import rcParams
import seaborn as sns

from IPython.display import display, HTML
import pandas as pd

import logging
from datetime import datetime, timedelta
import pandas as pd

from common_utils.notebook_utils import sign_notebook

pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 200)
from pandas.io.json import json_normalize

rcParams['figure.figsize'] = 15, 8

sns.set(rc={'figure.figsize':(12,6)})

sns.set(style="whitegrid", color_codes=True)
sns.despine()


from dbutils.query_utils import get_interval_clauses, run_select
from dbutils.utils import get_nabu_payments_client, get_nabu_ledger_client
from dbutils.query_utils import get_select_query, run_select, get_interval_clauses
from customers_analytics.fraud_analysis.fraud_db_utils import get_fraud_client
from customers_analytics.nabu.nabu_db_utils import (
    get_nabu_client_internal, 
    get_nabu_backoffice_client, 
    get_nabu_client, 
    get_nabu_client_private, 
    get_nabu_backoffice_client_prod, 
    categorize_blockchain_error_reasons
)

INFO:root:Role:data-science Environment:internal

In [5]:
client_internal = get_nabu_client_internal()

WARNING:root:trying to replace '-' in service-account name

In [45]:
query = \
'''
with created_cards as (
SELECT 
     distinct
     id
    ,user_id
    ,date_trunc('day', created_at) as created_at_day
    ,to_timestamp(to_char(created_at, 'yyyy-MM-dd HH24'), 'yyyy-MM-dd HH24') as created_at_dayhour
    --,to_char(date_trunc('day', created_at), 'yyyy-MM-dd') created_at
FROM card_additions
WHERE lower(state) = 'created'
),
gr_created_cards as (
SELECT 
     user_id
    --,created_at
    ,created_at_day
    ,created_at_dayhour
    ,count(id) OVER cum_per_dayhour AS cum_amt_cards_per_dayhour
    ,count(id) OVER cum_last_seven_h AS cum_amt_cards_last_seven_h
FROM created_cards
WINDOW cum_last_seven_h AS (PARTITION BY user_id
                               ORDER BY created_at_dayhour ASC
                               RANGE BETWEEN INTERVAL '7 hours' PRECEDING
                                         AND CURRENT ROW),
       cum_per_dayhour AS (PARTITION BY user_id
                               ORDER BY created_at_dayhour ASC
                               ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)                              
--ORDER BY user_id, created_at, cum_amt asc
),
card_pay_fraud_stats as (
SELECT 
     user_id
    ,card_type
    ,usd_amount
    ,to_timestamp(to_char(created_at, 'yyyy-MM-dd HH24'), 'yyyy-MM-dd HH24') as created_at_dayhour
FROM card_payments_fraud_stats
),
gr_card_pay_fraud_stats as (
SELECT
     user_id
    ,card_type
    ,created_at_dayhour
    ,sum(usd_amount) as sum_usd_amount 
FROM card_pay_fraud_stats
GROUP BY user_id, card_type, created_at_dayhour
--order by created_at, sum_usd_amount desc
)
SELECT 
     gr_cards.user_id
    ,gr_cards.created_at_day 
    ,gr_cards.created_at_dayhour
    ,gr_cards.cum_amt_cards_per_dayhour
    ,gr_cards.cum_amt_cards_last_seven_h
    ,gr_stats.sum_usd_amount    
    ,gr_stats.card_type
FROM gr_created_cards as gr_cards
left join gr_card_pay_fraud_stats as gr_stats 
on gr_cards.user_id = gr_stats.user_id
and gr_cards.created_at_dayhour = gr_stats.created_at_dayhour
ORDER BY gr_cards.created_at_day, 
         gr_cards.created_at_dayhour,
         gr_cards.cum_amt_cards_per_dayhour ASC
'''

In [46]:
df = client_internal.dataframe_from_query(query)

In [48]:
df[df["cum_amt_cards_last_seven_h"]>2]

,user_id,created_at_day,created_at_dayhour,cum_amt_cards_per_dayhour,cum_amt_cards_last_seven_h,sum_usd_amount,card_type
4,29763f0b-ed9c-41d2-861e-caed7f51cbff,2020-05-07,2020-05-07 09:00:00+00:00,3,3,NaN,None
5,158bf422-8d71-40f3-928c-ba6a166bf7b9,2020-05-07,2020-05-07 10:00:00+00:00,1,3,6.19,visa
6,158bf422-8d71-40f3-928c-ba6a166bf7b9,2020-05-07,2020-05-07 10:00:00+00:00,2,3,6.19,visa
7,4dfb7bf4-53fc-4143-bf91-e15a1cb3b3dd,2020-05-07,2020-05-07 10:00:00+00:00,2,3,6.19,master_card
8,4dfb7bf4-53fc-4143-bf91-e15a1cb3b3dd,2020-05-07,2020-05-07 10:00:00+00:00,3,3,6.19,master_card
...,...,...,...,...,...,...,...
1812676,47aeb17b-eb76-4a63-972b-d9797ff198d2,2022-05-13,2022-05-13 07:00:00+00:00,12,3,NaN,None
1812678,47aeb17b-eb76-4a63-972b-d9797ff198d2,2022-05-13,2022-05-13 07:00:00+00:00,13,3,NaN,None
1812679,47aeb17b-eb76-4a63-972b-d9797ff198d2,2022-05-13,2022-05-13 07:00:00+00:00,14,3,NaN,None
1812685,433c013f-3ab1-40af-b8db-fca3e19fa712,2022-05-13,2022-05-13 07:00:00+00:00,92,3,NaN,None
1812686,433c013f-3ab1-40af-b8db-fca3e19fa712,2022-05-13,2022-05-13 07:00:00+00:00,93,3,NaN,None

In [49]:
df[df["user_id"]=='a106ed76-f18c-44b6-9923-77b01dd11a99']

,user_id,created_at_day,created_at_dayhour,cum_amt_cards_per_dayhour,cum_amt_cards_last_seven_h,sum_usd_amount,card_type
1707272,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-08,2022-04-08 16:00:00+00:00,1,2,NaN,None
1707330,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-08,2022-04-08 16:00:00+00:00,2,2,NaN,None
1708980,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-09,2022-04-09 05:00:00+00:00,3,1,56.75,master_card
1709884,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-09,2022-04-09 14:00:00+00:00,4,1,5.00,master_card
1710905,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-09,2022-04-09 21:00:00+00:00,5,2,NaN,None
1712204,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-10,2022-04-10 11:00:00+00:00,6,1,NaN,None
1712338,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-10,2022-04-10 12:00:00+00:00,7,2,NaN,None
1712996,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-10,2022-04-10 17:00:00+00:00,8,3,NaN,None
1715958,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-11,2022-04-11 18:00:00+00:00,9,1,147.75,master_card
1716190,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-11,2022-04-11 19:00:00+00:00,10,2,141.84,master_card
1717191,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,11,8,NaN,None
1717192,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,12,8,NaN,None
1717193,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,13,8,NaN,None
1717194,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,14,8,NaN,None
1717195,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,15,8,NaN,None
1717197,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,16,8,NaN,None
1717198,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 02:00:00+00:00,17,8,NaN,None
1717273,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 03:00:00+00:00,18,13,NaN,None
1717274,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 03:00:00+00:00,19,13,NaN,None
1717276,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 03:00:00+00:00,20,13,NaN,None
1717280,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 03:00:00+00:00,21,13,NaN,None
1717281,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 03:00:00+00:00,22,13,NaN,None
1717282,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 03:00:00+00:00,23,13,NaN,None
1717355,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 04:00:00+00:00,24,15,14.37,master_card
1717356,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 04:00:00+00:00,25,15,14.37,master_card
1717447,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 05:00:00+00:00,26,16,NaN,None
1717572,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 06:00:00+00:00,27,18,64.00,master_card
1717573,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 06:00:00+00:00,28,18,64.00,master_card
1719727,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 19:00:00+00:00,29,2,220.00,master_card
1719728,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-12,2022-04-12 19:00:00+00:00,30,2,220.00,master_card
1720905,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 06:00:00+00:00,31,4,593.41,master_card
1720906,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 06:00:00+00:00,32,4,593.41,master_card
1720908,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 06:00:00+00:00,33,4,593.41,master_card
1720909,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 06:00:00+00:00,34,4,593.41,master_card
1721003,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 07:00:00+00:00,35,7,345.85,master_card
1721004,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 07:00:00+00:00,36,7,345.85,master_card
1721005,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 07:00:00+00:00,37,7,345.85,master_card
1721431,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 11:00:00+00:00,38,8,NaN,None
1721720,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 13:00:00+00:00,39,9,NaN,None
1721878,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 14:00:00+00:00,40,7,NaN,None
1721879,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 14:00:00+00:00,41,7,NaN,None
1722592,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 18:00:00+00:00,42,5,699.00,master_card
1722964,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 20:00:00+00:00,43,5,NaN,None
1723135,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-13,2022-04-13 21:00:00+00:00,44,5,NaN,None
1724315,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-14,2022-04-14 07:00:00+00:00,45,1,NaN,None
1724965,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-14,2022-04-14 12:00:00+00:00,46,2,NaN,None
1725507,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-14,2022-04-14 15:00:00+00:00,47,2,NaN,None
1726197,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-14,2022-04-14 19:00:00+00:00,48,3,NaN,None
1727470,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 05:00:00+00:00,49,1,NaN,None
1727825,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 08:00:00+00:00,50,2,NaN,None
1727949,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 09:00:00+00:00,51,3,NaN,None
1728194,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 11:00:00+00:00,52,4,NaN,None
1729179,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 17:00:00+00:00,53,2,NaN,None
1729327,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 18:00:00+00:00,54,3,NaN,None
1729929,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-15,2022-04-15 22:00:00+00:00,55,3,NaN,None
1730784,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-16,2022-04-16 06:00:00+00:00,56,1,NaN,None
1730880,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-16,2022-04-16 07:00:00+00:00,57,2,NaN,None
1731438,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-16,2022-04-16 12:00:00+00:00,58,3,NaN,None
1732011,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-16,2022-04-16 16:00:00+00:00,59,2,NaN,None
1733625,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-17,2022-04-17 06:00:00+00:00,60,1,NaN,None
1733713,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-17,2022-04-17 07:00:00+00:00,61,3,NaN,None
1733714,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-17,2022-04-17 07:00:00+00:00,62,3,NaN,None
1734184,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-17,2022-04-17 12:00:00+00:00,63,4,NaN,None
1735443,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-17,2022-04-17 21:00:00+00:00,64,1,NaN,None
1736836,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-18,2022-04-18 12:00:00+00:00,65,1,NaN,None
1736964,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-18,2022-04-18 13:00:00+00:00,66,2,NaN,None
1737106,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-18,2022-04-18 14:00:00+00:00,67,3,NaN,None
1744718,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-20,2022-04-20 21:00:00+00:00,68,1,NaN,None
1746445,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-21,2022-04-21 13:00:00+00:00,69,1,NaN,None
1747452,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-21,2022-04-21 19:00:00+00:00,70,3,925.00,master_card
1747453,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-21,2022-04-21 19:00:00+00:00,71,3,925.00,master_card
1748766,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-22,2022-04-22 06:00:00+00:00,72,1,NaN,None
1749776,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-22,2022-04-22 14:00:00+00:00,73,1,NaN,None
1750563,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-22,2022-04-22 18:00:00+00:00,74,2,NaN,None
1757025,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-25,2022-04-25 08:00:00+00:00,75,1,NaN,None
1758385,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-25,2022-04-25 18:00:00+00:00,76,1,492.00,master_card
1758548,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-25,2022-04-25 19:00:00+00:00,77,2,NaN,None
1758735,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-25,2022-04-25 20:00:00+00:00,78,3,NaN,None
1759843,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 05:00:00+00:00,79,2,320.00,master_card
1759844,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 05:00:00+00:00,80,2,320.00,master_card
1759925,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 06:00:00+00:00,81,3,NaN,None
1760021,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 07:00:00+00:00,82,4,NaN,None
1760235,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 09:00:00+00:00,83,5,NaN,None
1760481,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 11:00:00+00:00,84,6,NaN,None
1761233,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 16:00:00+00:00,85,3,NaN,None
1761967,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-26,2022-04-26 20:00:00+00:00,86,2,NaN,None
1762978,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-27,2022-04-27 05:00:00+00:00,87,1,NaN,None
1763255,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-27,2022-04-27 08:00:00+00:00,88,2,NaN,None
1763982,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-27,2022-04-27 14:00:00+00:00,89,2,NaN,None
1766141,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-28,2022-04-28 05:00:00+00:00,90,1,NaN,None
1767525,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-28,2022-04-28 16:00:00+00:00,91,3,NaN,None
1767526,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-28,2022-04-28 16:00:00+00:00,92,3,NaN,None
1767527,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-28,2022-04-28 16:00:00+00:00,93,3,NaN,None
1769471,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-29,2022-04-29 07:00:00+00:00,94,2,320.00,master_card
1769472,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-29,2022-04-29 07:00:00+00:00,95,2,320.00,master_card
1769801,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-29,2022-04-29 10:00:00+00:00,96,3,NaN,None
1771282,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-29,2022-04-29 19:00:00+00:00,97,1,NaN,None
1771498,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-29,2022-04-29 20:00:00+00:00,98,2,NaN,None
1772678,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-04-30,2022-04-30 07:00:00+00:00,99,1,NaN,None
1775404,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-01,2022-05-01 09:00:00+00:00,100,1,NaN,None
1777854,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-02,2022-05-02 09:00:00+00:00,101,1,NaN,None
1783322,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-04,2022-05-04 04:00:00+00:00,102,1,230.00,master_card
1783396,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-04,2022-05-04 05:00:00+00:00,103,2,230.00,master_card
1783476,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-04,2022-05-04 06:00:00+00:00,104,3,NaN,None
1792751,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-07,2022-05-07 07:00:00+00:00,105,1,NaN,None
1792852,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-07,2022-05-07 08:00:00+00:00,106,2,NaN,None
1804664,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-11,2022-05-11 08:00:00+00:00,107,5,694.00,master_card
1804665,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-11,2022-05-11 08:00:00+00:00,108,5,694.00,master_card
1804666,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-11,2022-05-11 08:00:00+00:00,109,5,694.00,master_card
1804667,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-11,2022-05-11 08:00:00+00:00,110,5,694.00,master_card
1804668,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-11,2022-05-11 08:00:00+00:00,111,5,694.00,master_card
1812276,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-13,2022-05-13 04:00:00+00:00,112,1,190.70,master_card
1812405,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-13,2022-05-13 05:00:00+00:00,113,3,172.00,master_card
1812406,a106ed76-f18c-44b6-9923-77b01dd11a99,2022-05-13,2022-05-13 05:00:00+00:00,114,3,172.00,master_card