In [2]:
import sys, os

In [3]:
sys.path

['/home/aektov/data-ops',
 '/home/aektov/.pyenv/versions/3.8.11/lib/python38.zip',
 '/home/aektov/.pyenv/versions/3.8.11/lib/python3.8',
 '/home/aektov/.pyenv/versions/3.8.11/lib/python3.8/lib-dynload',
 '',
 '/home/aektov/.local/share/virtualenvs/python-data-science-mirror-JM_PQ88B/lib/python3.8/site-packages',
 '/home/aektov/python-data-science-mirror/src/on_chain_insights',
 '/home/aektov/python-data-science-mirror/src/common_utils',
 '/home/aektov/python-data-science-mirror/src/customers_analytics',
 '/home/aektov/python-data-science-mirror/src/ab_testing',
 '/home/aektov/python-data-science-mirror/src/tracking',
 '/home/aektov/python-data-science-mirror/src/modelling',
 '/home/aektov/python-data-science-mirror/src/dashboards',
 '/home/aektov/python-data-science-mirror/src/wallet_segmentation',
 '/home/aektov/python-data-science-mirror/src/trading',
 '/home/aektov/python-data-science-mirror/src/on_chain_analysis',
 '/home/aektov/python-data-science-mirror/src/marketdatastorage',
 '/home/aektov/python-data-science-mirror/src/feature_db',
 '/home/aektov/python-data-science-mirror/src/mm_reports',
 '/home/aektov/python-data-science-mirror/src/dbutils',
 '/home/aektov/python-data-science-mirror/src/etl/dags',
 '/home/aektov/python-data-science-mirror/src/db_schemas']

In [1]:
from common_utils.utils import chunks
from tqdm import tqdm
from matplotlib import pyplot as plt
from pylab import rcParams
import seaborn as sns

from IPython.display import display, HTML
import pandas as pd

import logging
from datetime import datetime, timedelta
import pandas as pd

from common_utils.notebook_utils import sign_notebook

pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 200)
from pandas.io.json import json_normalize

rcParams['figure.figsize'] = 15, 8

sns.set(rc={'figure.figsize':(12,6)})

sns.set(style="whitegrid", color_codes=True)
sns.despine()


from dbutils.query_utils import get_interval_clauses, run_select
from dbutils.utils import get_nabu_payments_client, get_nabu_ledger_client
from dbutils.query_utils import get_select_query, run_select, get_interval_clauses
from customers_analytics.fraud_analysis.fraud_db_utils import get_fraud_client
from customers_analytics.nabu.nabu_db_utils import (
    get_nabu_client_internal, 
    get_nabu_backoffice_client, 
    get_nabu_client, 
    get_nabu_client_private, 
    get_nabu_backoffice_client_prod, 
    categorize_blockchain_error_reasons
)

INFO:root:Role:data-science Environment:internal

## Check roles based on variables from user env

In [4]:
from dbutils.vault import get_vault_client
from dbutils.roles.sources import initialise_sources, role

initialise_sources()
# initialise_sources("data-science", "internal")

# role

INFO:root:Role:data-science Environment:internal

In [5]:
print(os.environ["APP_ROLE"])

data-science

In [4]:
vault_url = os.environ.get("VAULT_ADDR")
vault_token = os.environ.get("VAULT_TOKEN")

vault_url, vault_token

('http://vault.service.consul:8200', 's.GXkEJYDP4YNaY62HIEMdSw3g')

## Parsing config file `internal.yml` associated with `APP_ROLE`

In [54]:
import yaml

filename = '/home/aektov/python-data-science-mirror/src/dbutils/dbutils/roles/etl/internal.yml'

with open(filename, "r") as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

In [20]:
config

{'role': 'etl',
 'environment': 'internal',
 'sources': {'market': {'type': 'bigtable',
   'credentials': 'vault://secret/bigtable/market/credentials?value',
   'instance': 'vault://secret/bigtable/market/instance?value',
   'project': 'vault://secret/bigtable/market/project?value'},
  'on-chain-activity': {'type': 'psql',
   'host': 'vault://secret/postgres/on-chain-activity/host?value',
   'db': 'vault://secret/postgres/on-chain-activity/db?value',
   'port': 'vault://secret/postgres/on-chain-activity/port?value',
   'username': 'on-c-a',
   'password': 'vault://secret/postgres/on-chain-activity/users/on-c-a/password?value'},
  'nabu-gateway': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-gateway/host?value',
   'db': 'vault://secret/postgres/nabu-gateway/db?value',
   'port': 'vault://secret/postgres/nabu-gateway/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/postgres/nabu-gateway/users/etl-ro/password?value'},
  'nabu-gateway-historic': {'type': 'psql',
   'db': 'nabu-gateway',
   'host': '10.50.0.250',
   'port': 5432,
   'username': 'etl-ro',
   'password': 'vault://secret/postgres/nabu-gateway/users/etl-ro/password?value'},
  'nabu-backoffice': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-backoffice/host?value',
   'db': 'vault://secret/postgres/nabu-backoffice/db?value',
   'port': 'vault://secret/postgres/nabu-backoffice/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/postgres/nabu-backoffice/users/etl-ro/password?value'},
  'charts-sanitized': {'type': 'psql',
   'host': 'vault://secret/postgres/charts-sanitized/host?value',
   'db': 'vault://secret/postgres/charts-sanitized/db?value',
   'port': 'vault://secret/postgres/charts-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/charts-sanitized/users/etl/password?value'},
  'charts-internal-sanitized': {'type': 'psql',
   'host': 'vault://secret/postgres/charts-sanitized/host?value',
   'db': 'charts_internal',
   'port': 'vault://secret/postgres/charts-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/charts-sanitized/users/etl/password?value'},
  'nabu-gateway-sanitized': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-gateway-sanitized/host?value',
   'db': 'vault://secret/postgres/nabu-gateway-sanitized/db?value',
   'port': 'vault://secret/postgres/nabu-gateway-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/nabu-gateway-sanitized/users/etl/password?value'},
  'internal-datahub': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-gateway-sanitized/host?value',
   'db': 'datahub',
   'port': 'vault://secret/postgres/nabu-gateway-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/nabu-gateway-sanitized/users/etl/password?value'},
  'nabu-backoffice-sanitized': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-backoffice-sanitized/host?value',
   'db': 'vault://secret/postgres/nabu-backoffice-sanitized/db?value',
   'port': 'vault://secret/postgres/nabu-backoffice-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/nabu-backoffice-sanitized/users/etl/password?value'},
  'nabu-private': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-private/host?value',
   'db': 'vault://secret/postgres/nabu-private/db?value',
   'port': 'vault://secret/postgres/nabu-private/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/nabu-private/users/etl/password?value'},
  'matomo-sanitized': {'type': 'psql',
   'host': 'vault://secret/postgres/matomo-sanitized/host?value',
   'db': 'vault://secret/postgres/matomo-sanitized/db?value',
   'port': 'vault://secret/postgres/matomo-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/matomo-sanitized/users/etl/password?value'},
  'xlm-analysis': {'type': 'psql',
   'host': 'vault://secret/postgres/xlm-analysis/host?value',
   'db': 'vault://secret/postgres/xlm-analysis/db?value',
   'port': 'vault://secret/postgres/xlm-analysis/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/xlm-analysis/users/etl/password?value'},
  'trading': {'type': 'psql',
   'host': 'vault://secret/postgres/trading/host?value',
   'db': 'vault://secret/postgres/trading/db?value',
   'port': 'vault://secret/postgres/trading/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/postgres/trading/users/etl-ro/password?value'},
  'matomo': {'type': 'mysql',
   'host': 'vault://secret/mysql/matomo/host?value',
   'db': 'vault://secret/mysql/matomo/db?value',
   'port': 'vault://secret/mysql/matomo/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/mysql/matomo/users/etl-ro/password?value'},
  'matomo-staging': {'type': 'mysql',
   'host': 'vault://secret/mysql/matomo-staging/host?value',
   'db': 'vault://secret/mysql/matomo-staging/db?value',
   'port': 'vault://secret/mysql/matomo-staging/port?value',
   'username': 'matomo-ro',
   'password': 'vault://secret/mysql/matomo-staging/users/matomo-ro/password?value'},
  'charts': {'type': 'mysql',
   'host': 'vault://secret/mysql/charts/host?value',
   'db': 'vault://secret/mysql/charts/db?value',
   'port': 'vault://secret/mysql/charts/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/mysql/charts/users/etl-ro/password?value'},
  'dev-charts-ds': {'type': 'mysql',
   'host': 'vault://secret/mysql/charts-ds-dev/host?value',
   'db': 'vault://secret/mysql/charts-ds-dev/db?value',
   'port': 'vault://secret/mysql/charts-ds-dev/port?value',
   'username': 'etl',
   'password': 'vault://secret/mysql/charts-ds-dev/users/etl/password?value'},
  'staging-charts-ds': {'type': 'mysql',
   'host': 'vault://secret/mysql/charts-ds-staging/host?value',
   'db': 'vault://secret/mysql/charts-ds-staging/db?value',
   'port': 'vault://secret/mysql/charts-ds-staging/port?value',
   'username': 'charts',
   'password': 'vault://secret/mysql/charts-ds-staging/users/charts/password?value'},
  'charts-ds': {'type': 'mysql',
   'host': 'vault://secret/mysql/charts-ds-production/host?value',
   'db': 'vault://secret/mysql/charts-ds-production/db?value',
   'port': 'vault://secret/mysql/charts-ds-production/port?value',
   'username': 'charts',
   'password': 'vault://secret/mysql/charts-ds-production/users/charts/password?value'},
  'charts-internal': {'type': 'mysql',
   'host': 'vault://secret/mysql/charts_internal/host?value',
   'db': 'vault://secret/mysql/charts_internal/db?value',
   'port': 'vault://secret/mysql/charts_internal/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/mysql/charts_internal/users/etl-ro/password?value'},
  'research-ingestion': {'type': 'service-account',
   'gcs-key': 'vault://secret/service-accounts/research-ingestion/gcs-key?value'},
  'models-bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/data-science-models-rw/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-data-science-models'},
  'acton': {'type': 'acton',
   'blob': 'vault://secret/apps/etl/api/acton?value'},
  'hot-wallet': {'type': 'mysql',
   'host': 'vault://secret/mysql/hot-wallet-replica-prod/host?value',
   'db': 'vault://secret/mysql/hot-wallet-replica-prod/db?value',
   'port': 'vault://secret/mysql/hot-wallet-replica-prod/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/mysql/hot-wallet-replica-prod/users/etl-ro/password?value'},
  'hot-wallet-treasury': {'type': 'mysql',
   'host': '10.132.0.112',
   'db': 'hot_wallet_treasury',
   'port': 10081,
   'username': 'etl-ro',
   'password': 'vault://secret/mysql/prod-hot-wallet-treasury-replica/users/etl-ro/password?value'},
  'features': {'type': 'psql',
   'host': 'vault://secret/postgres/features/host?value',
   'db': 'vault://secret/postgres/features/db?value',
   'port': 'vault://secret/postgres/features/port?value',
   'username': 'postgres',
   'password': 'vault://secret/postgres/features/users/postgres/password?value'},
  'model-features': {'type': 'psql',
   'host': 'vault://secret/postgres/model-features/host?value',
   'db': 'vault://secret/postgres/model-features/db?value',
   'port': 'vault://secret/postgres/model-features/port?value',
   'username': 'postgres',
   'password': 'vault://secret/postgres/model-features/users/postgres/password?value'},
  'features-private': {'type': 'psql',
   'host': 'vault://secret/postgres/features-private/host?value',
   'db': 'vault://secret/postgres/features-private/db?value',
   'port': 'vault://secret/postgres/features-private/port?value',
   'username': 'postgres',
   'password': 'vault://secret/postgres/features-private/users/postgres/password?value'},
  'on-chain-proto-bucket-staging': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-staging',
   'bucket-name': 'bc-on-chain-analysis-staging'},
  'on-chain-proto-bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-prod',
   'bucket-name': 'bc-on-chain-analysis-prod'},
  'staging-nabu-gateway': {'type': 'psql',
   'host': 'vault://secret/postgres/staging-nabu-gateway/host?value',
   'db': 'vault://secret/postgres/staging-nabu-gateway/db?value',
   'port': 'vault://secret/postgres/staging-nabu-gateway/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/staging-nabu-gateway/users/etl/password?value'},
  'staging-nabu-backoffice': {'type': 'psql',
   'host': 'vault://secret/postgres/staging-nabu-backoffice/host?value',
   'db': 'vault://secret/postgres/staging-nabu-backoffice/db?value',
   'port': 'vault://secret/postgres/staging-nabu-backoffice/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/staging-nabu-backoffice/users/etl/password?value'},
  'staging-nabu-ledger': {'type': 'psql',
   'host': 'vault://secret/postgres/staging-nabu-ledger/host?value',
   'db': 'vault://secret/postgres/staging-nabu-ledger/db?value',
   'port': 'vault://secret/postgres/staging-nabu-ledger/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/staging-nabu-ledger/users/etl/password?value'},
  'staging-nabu-payments': {'type': 'psql',
   'host': 'vault://secret/postgres/staging-nabu-payments/host?value',
   'db': 'vault://secret/postgres/staging-nabu-payments/db?value',
   'port': 'vault://secret/postgres/staging-nabu-payments/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/staging-nabu-payments/users/etl/password?value'},
  'staging-mercury-order-service': {'type': 'psql',
   'host': 'vault://secret/postgres/staging-mercury-order-service/host?value',
   'db': 'vault://secret/postgres/staging-mercury-order-service/db?value',
   'port': 'vault://secret/postgres/staging-mercury-order-service/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/staging-mercury-order-service/users/etl/password?value'},
  'nabu-ledger': {'type': 'psql',
   'host': 'vault://secret/postgres/prod-nabu-ledger/host?value',
   'db': 'vault://secret/postgres/prod-nabu-ledger/db?value',
   'port': 'vault://secret/postgres/prod-nabu-ledger/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/prod-nabu-ledger/users/etl/password?value'},
  'nabu-payments': {'type': 'psql',
   'host': 'vault://secret/postgres/prod-nabu-payments/host?value',
   'db': 'vault://secret/postgres/prod-nabu-payments/db?value',
   'port': 'vault://secret/postgres/prod-nabu-payments/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/prod-nabu-payments/users/etl/password?value'},
  'mercury-events': {'type': 'psql',
   'host': 'vault://secret/postgres/prod-mercury-events/host?value',
   'db': 'vault://secret/postgres/prod-mercury-events/db?value',
   'port': 'vault://secret/postgres/prod-mercury-events/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/prod-mercury-events/users/etl/password?value'},
  'iterable': {'type': 'iterable',
   'api_key': 'vault://secret/apps/etl/api/iterable?api_key'},
  'iterable-dev': {'type': 'iterable',
   'api_key': 'vault://secret/apps/etl/api/iterable-dev?api_key'},
  'crypto-compare': {'type': 'api-key',
   'api_key': 'vault://secret/apps/etl/api/crypto-compare?api_key'},
  'loanscan': {'type': 'loanscan',
   'api_key': 'vault://secret/apps/etl/api/loanscan?api_key'},
  'binance-lending': {'type': 'api-key-secret',
   'api_key': 'vault://secret/apps/etl/api/binance-lending?api_key',
   'secret_key': 'vault://secret/apps/etl/api/binance-lending?secret_key'},
  'bitfinex-lending': {'type': 'api-key-secret',
   'api_key': 'vault://secret/apps/etl/api/bitfinex-lending?api_key',
   'secret_key': 'vault://secret/apps/etl/api/bitfinex-lending?secret_key'},
  'kraken-lending': {'type': 'api-key-secret',
   'api_key': 'vault://secret/apps/etl/api/kraken-lending?api_key',
   'secret_key': 'vault://secret/apps/etl/api/kraken-lending?secret_key'},
  'nabu-fraud': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-fraud-prod/host?value',
   'db': 'vault://secret/postgres/nabu-fraud-prod/db?value',
   'port': 'vault://secret/postgres/nabu-fraud-prod/port?value',
   'username': 'nabu-fraud-ro',
   'password': 'vault://secret/postgres/nabu-fraud-prod/users/nabu-fraud-ro/password?value'},
  'slack-api': {'type': 'slack',
   'oauth-token': 'vault://secret/apps/etl/slack/oauth?value'},
  'firebase-bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-data-science-big-query'},
  'firebase-bigquery': {'type': 'bigquery',
   'service_account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'fir-production'},
  'firebase-staging-bigquery': {'type': 'bigquery',
   'service_account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'fir-staging-92d79'},
  'staging-bitcoin-bch': {'type': 'mysql',
   'host': 'vault://secret/mysql/bitcoin-bch/host?value',
   'db': 'vault://secret/mysql/bitcoin-bch/db?value',
   'port': 'vault://secret/mysql/bitcoin-bch/port?value',
   'username': 'etl',
   'password': 'vault://secret/mysql/bitcoin-bch/users/etl/password?value'},
  'bitcoin-bch': {'type': 'mysql',
   'host': 'vault://secret/mysql/bitcoin-bch-production/host?value',
   'db': 'vault://secret/mysql/bitcoin-bch-production/db?value',
   'port': 'vault://secret/mysql/bitcoin-bch-production/port?value',
   'username': 'etl',
   'password': 'vault://secret/mysql/bitcoin-bch-production/users/etl/password?value'},
  'staging-bitcoin-core': {'type': 'mysql',
   'host': 'vault://secret/mysql/bitcoin-core-staging/host?value',
   'db': 'piuk_bitcoin',
   'port': 'vault://secret/mysql/bitcoin-core-staging/port?value',
   'username': 'etl-bitcoin-core-ro',
   'password': 'vault://secret/mysql/bitcoin-core-staging/users/etl-bitcoin-core-ro/password?value'},
  'bitcoin-core': {'type': 'mysql',
   'host': 'vault://secret/mysql/bitcoin-core-production/host?value',
   'db': 'piuk_bitcoin',
   'port': 'vault://secret/mysql/bitcoin-core-production/port?value',
   'username': 'etl-bitcoin-core-ro',
   'password': 'vault://secret/mysql/bitcoin-core-production/users/etl-bitcoin-core-ro/password?value'},
  'staging-lending': {'type': 'psql',
   'host': 'vault://secret/postgres/staging-lending/host?value',
   'db': 'vault://secret/postgres/staging-lending/db?value',
   'port': 'vault://secret/postgres/staging-lending/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/staging-lending/users/etl/password?value'},
  'internal-lending': {'type': 'psql',
   'host': 'vault://secret/postgres/lending/host?value',
   'db': 'vault://secret/postgres/lending/db?value',
   'port': 'vault://secret/postgres/lending/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/lending/users/etl/password?value'},
  'zendesk': {'type': 'zendesk',
   'email': 'vault://secret/apps/etl/api/zendesk/email?value',
   'token': 'vault://secret/apps/etl/api/zendesk/token?value'},
  'nabu-auth': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-auth/host?value',
   'db': 'vault://secret/postgres/nabu-auth/db?value',
   'port': 'vault://secret/postgres/nabu-auth/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/nabu-auth/users/etl/password?value'},
  'influx-staging-explorer': {'type': 'influx',
   'host': 'vault://secret/influxdb/staging-influxdb-apps/host?value',
   'db': 'telegraf',
   'port': 8086,
   'username': 'etl_ro',
   'password': 'vault://secret/influxdb/staging-influxdb-apps/users/etl_ro/password?value'},
  'influx-prod-explorer': {'type': 'influx',
   'host': 'vault://secret/influxdb/prod-influxdb-apps/host?value',
   'db': 'telegraf',
   'port': 8086,
   'username': 'etl_ro',
   'password': 'vault://secret/influxdb/prod-influxdb-apps/users/etl_ro/password?value'},
  'lending': {'type': 'psql',
   'host': 'vault://secret/postgres/prod-lending/host?value',
   'db': 'vault://secret/postgres/prod-lending/db?value',
   'port': 'vault://secret/postgres/prod-lending/port?value',
   'username': 'etl-ro',
   'password': 'vault://secret/postgres/prod-lending/users/etl-ro/password?value'},
  'email': {'type': 'email',
   'username': 'vault://secret/apps/etl/email/username?value',
   'password': 'vault://secret/apps/etl/email/password?value'},
  'mm_reports': {'type': 'psql',
   'host': 'vault://secret/postgres/nabu-gateway-sanitized/host?value',
   'db': 'mm_reports',
   'port': 'vault://secret/postgres/nabu-gateway-sanitized/port?value',
   'username': 'etl',
   'password': 'vault://secret/postgres/nabu-gateway-sanitized/users/etl/password?value'},
  'mm_reports_bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/data-science-models-rw/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-mm-reports'},
  'mm_report_bucket_wintermute': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/data-science-models-ro/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-mm-report-wintermute'},
  'mm_report_bucket_bluefire': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/data-science-models-ro/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-mm-report-bluefire'},
  'mm_report_bucket_dunamis': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/data-science-models-ro/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-mm-report-dunamis'},
  'mm_report_bucket_towerbc': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/data-science-models-ro/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-mm-report-towerbc'},
  'lob-bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-data-science-lob'},
  'fast-lob-bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-data-science-fast-lob'},
  'loan-bucket': {'type': 'bucket',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-internal',
   'bucket-name': 'blockchain-loan-updates'},
  'lending-master-sheet': {'type': 'google-sheet',
   'service-account': 'vault://secret/service-accounts/research-ingestion/gcs-key?value',
   'project': 'blockchain-internal',
   'spreadsheet-id': 'vault://secret/apps/etl/spreadsheet-ids/lending-master?value'},

In [5]:
role.sources["nabu-gateway"]._config

WARNING:root:trying to replace '-' in service-account name

{'type': 'psql',
 'host': 'vault://secret/postgres/nabu-gateway/host?value',
 'db': 'vault://secret/postgres/nabu-gateway/db?value',
 'port': 'vault://secret/postgres/nabu-gateway/port?value',
 'username': 'etl-ro',
 'password': 'vault://secret/postgres/nabu-gateway/users/etl-ro/password?value'}

In [6]:
path = role.sources["nabu-gateway"]._config["host"].split("/", 2)[2].split("?")[0]

client = get_vault_client()
client.read(path)["data"]

{'value': '10.132.0.112'}

In [7]:
pgclient = role.sources["nabu-gateway"]

In [8]:
pgclient.db

'vault://secret/postgres/nabu-gateway/db?value'

In [9]:
pgclient._config

{'type': 'psql',
 'host': 'vault://secret/postgres/nabu-gateway/host?value',
 'db': 'vault://secret/postgres/nabu-gateway/db?value',
 'port': 'vault://secret/postgres/nabu-gateway/port?value',
 'username': 'etl-ro',
 'password': 'vault://secret/postgres/nabu-gateway/users/etl-ro/password?value'}

In [12]:
pgclient._client

In [48]:
pg = pgclient.create_client()

## UDF: Test Custom Update Method with specified Client

In [10]:
# from customers_analytics.nabu.internal_tables.payments import update_payments_account

client = get_nabu_payments_client()
client_internal = get_nabu_client_internal()

In [122]:
def update_payments_account(start_date, end_date, client=None):
    """Get the account information required from payments data into the data needed for the internal payments_account replica
    Parameters
    ----------
    start_date : dt.datetime
    end_date : dt.datetime
    client : PostgresClient (default=None)
        Client connected with the payments db. If None, the client is created by the function
    Returns
    -------
    payments_account_df : pd.DataFrame
        final dataframe that will match what is in the payments_account internal table
    """
    
    if client is None:
        client = get_nabu_payments_client()
        
    payments_account_df = run_select(
        client=client,
        table="payments.account",
        cols=[
            "id",
            "type",
            "partner",
            "product",
            "account_ref",
            "currency",
            "agent_ref",
            # "payments.account.extra_attributes",
            "\"user\" as user_id",
            #"extra_attributes ->> 'name' as card_name",
            #"extra_attributes -> 'card' ->> 'holder_name' as card_holder_name",
            "extra_attributes -> 'card' ->> 'type' as card_type",           
            "extra_attributes -> 'card' ->> 'bin' as card_bin",
            "extra_attributes -> 'card' ->> 'issuer' as card_issuer",
            "extra_attributes -> 'card' ->> 'issuer_country' as card_issuer_country",
            "extra_attributes -> 'card' ->> 'funding_source' as card_funding_source",
            "extra_attributes ->> 'card_acquirer_name' as card_acquirer_name",
            "extra_attributes -> 'ach_details' ->> 'bankName' as ach_bankName",
            #"extra_attributes -> 'ach_details' ->> 'accountName' ach_accountName",
            "extra_attributes -> 'ach_details' ->> 'bankAccountType' ach_bankAccountType",
            #"extra_attributes ->> 'email' as email",
            "extra_attributes -> 'billing_address' ->> 'city' as billing_city",
            "extra_attributes -> 'billing_address' ->> 'state' as billing_state",
            "extra_attributes -> 'billing_address' ->> 'country' as billing_country",
            # "extra_attributes -> 'billing_address' ->> 'postCode' as postCode",
            # "extra_attributes -> 'billing_address' ->> trim(concat('line1', ' ', 'line2')) as address",            
            "inserted_at",
            "updated_at",
            "last_state",
        ],
        between_clauses={"inserted_at": (start_date, end_date)},
        #null_clauses={"extra_attributes -> 'ach_details' ->> 'accountName'": False}
    )

    payments_account_df = payments_account_df.sort_values("inserted_at").drop_duplicates(
        "id", keep="first"
    )

    return payments_account_df

In [123]:
start_date = "2022-05-01T00:00+0000"
end_date = "2022-05-02T00:00+0000"

In [124]:
payments_account_df = update_payments_account(start_date, end_date)

In [144]:
payments_account_df.head()

,id,type,partner,product,account_ref,currency,agent_ref,user_id,card_type,card_bin,card_issuer,card_issuer_country,card_funding_source,card_acquirer_name,ach_bankname,ach_bankaccounttype,billing_city,billing_state,billing_country,inserted_at,updated_at,last_state
4,34117193-52a2-42bb-b5eb-29e36ad9d9b9,VIRTUAL_REFERENCE,SILVERGATE,SIMPLEBUY,BCY7DWXV,USD,5090015388,3d26fd85-cc3f-4610-a9a9-957b76993095,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 00:00:02.657,2022-05-01 00:00:02.657,ACTIVE
17,0ec04bbc-68cc-4c44-bc9b-33ebcf470c35,VIRTUAL_REFERENCE,CARDPROVIDER,SIMPLEBUY,52698f5d-a0d5-4d61-815b-74b2cd916542,USD,None,52698f5d-a0d5-4d61-815b-74b2cd916542,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 00:00:13.716,2022-05-01 00:00:13.716,ACTIVE
15,fffef966-f6b3-4b80-85ed-b2db69d47e2f,VIRTUAL_REFERENCE,HWS,SIMPLEBUY,3QH6bL9eyuNaNrQBspyKZxJ812NEzunQ8Z,BTC,None,0025d27d-5a19-4ad0-8a19-12ced0f8f377,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 00:00:22.062,2022-05-01 00:00:22.062,ACTIVE
10999,031187f4-d664-4583-838c-7bb4f4b07f8e,BENEFICIARY,PLAID,NONE,ach_account,USD,RvpYkbwbNwsDrkjxk4xDUZoJdpYewwUyAx3bN,83e9d651-a8c6-43b5-a497-be8aed26635f,None,None,None,None,None,None,Bank of America,CHECKING,None,None,None,2022-05-01 00:00:31.032,2022-05-02 13:08:04.922,ACTIVE
18,127b775d-e2b1-4b68-8c34-7b8a76af32d5,BENEFICIARY,CARDPROVIDER,NONE,card,USD,ae9fa7bf-0ca3-4853-b7dc-6de6902a84cf,05a64aa2-a1dc-4701-be2f-9fb3955e09d3,visa,419690,BANCO INVEX S.A. INSTITUCION DE BANCA MULTIPLE,MX,credit,STRIPE,None,None,Aguascalientes,,MX,2022-05-01 00:00:37.840,2022-05-01 00:00:43.213,BLOCKED

## Work with extracted string vlaues: str length checker

In [107]:
__MAX__STR_LEN__ = 300

In [101]:
for col, df_ in payments_account_df.items():
    if (findx := df_.first_valid_index()): 
        val = df_.loc[findx]
    else: 
        print("None Column Detected")
        val = None
    if isinstance(val, str):
        if payments_account_df[col].str.len().max() >= __MAX__STR_LEN__:
            idx = payments_account_df[payments_account_df[col].str.len() >= __MAX__STR_LEN__].index
            payments_account_df.loc[idx, col] = payments_account_df.loc[idx, col].apply(lambda x: x[:__MAX__STR_LEN__])

None Column Detected
None Column Detected

In [79]:
for col, df_ in payments_account_df.items():
    val = df_.loc[df_.first_valid_index()] 
    if isinstance(val, str):
        max_ = payments_account_df[~payments_account_df[col].isnull()][col].str.len().max()
        print("{} --> max len: {}".format(col, max_))

id --> max len: 36
type --> max len: 17
partner --> max len: 18
product --> max len: 9
account_ref --> max len: 104
currency --> max len: 6
agent_ref --> max len: 52
current_user --> max len: 3
card_holder_name --> max len: 126
card_type --> max len: 11
card_bin --> max len: 6
card_issuer --> max len: 93
card_issuer_country --> max len: 2
card_funding_source --> max len: 14
card_acquirer_name --> max len: 14
ach_bankname --> max len: 62
ach_bankaccounttype --> max len: 8
billing_city --> max len: 112
billing_state --> max len: 1024
billing_country --> max len: 2
last_state --> max len: 15

In [71]:
payments_account_df[payments_account_df.billing_state.str.len() > 1000].billing_state[236917]

'{"version":"1.0.7","state":{"colors":{"scheme":{"background":"#ffffff","symbol":"#c3a700","symbolContent":"#fff","icon":"#000","name":"#65525b","nameShadow":"#65525b","nameWithShadow":"#fff","divider":"#65525b","slogan":"#65525b"},"background":{"hue":0,"saturation":0,"value":1,"gradient":{"active":false,"range":0.3808157731797498,"style":0,"type":1,"radius":0.75,"reverse":false,"angle":315}},"symbol":{"hue":0.14273504273504276,"saturation":1,"value":0.7647058823529411,"gradient":{"active":false,"range":0.573723569479605,"style":2,"type":0,"radius":1,"reverse":false,"angle":270}},"symbolContent":{"hue":0,"saturation":0,"value":1,"gradient":{"active":false,"range":0.6105502873850108,"style":3,"type":0,"radius":0.75,"reverse":false,"angle":270}},"icon":{"hue":0,"saturation":0,"value":1},"name":{"hue":0,"saturation":0,"value":1},"nameShadow":{"hue":0.9210526315789473,"saturation":0.188118811881188,"value":0.396078431372549,"gradient":{"active":false,"range":0.49797410386458024,"style":1,"type":0,"radius":0.75,"re'

In [146]:
payments_account_df[~payments_account_df.billing_country.isnull()].head()

,id,type,partner,product,account_ref,currency,agent_ref,user_id,card_type,card_bin,card_issuer,card_issuer_country,card_funding_source,card_acquirer_name,ach_bankname,ach_bankaccounttype,billing_city,billing_state,billing_country,inserted_at,updated_at,last_state
18,127b775d-e2b1-4b68-8c34-7b8a76af32d5,BENEFICIARY,CARDPROVIDER,NONE,card,USD,ae9fa7bf-0ca3-4853-b7dc-6de6902a84cf,05a64aa2-a1dc-4701-be2f-9fb3955e09d3,visa,419690,BANCO INVEX S.A. INSTITUCION DE BANCA MULTIPLE,MX,credit,STRIPE,None,None,Aguascalientes,,MX,2022-05-01 00:00:37.840,2022-05-01 00:00:43.213,BLOCKED
22,7b3c2fa4-272a-4e1c-bb74-c852028f7e87,BENEFICIARY,CARDPROVIDER,NONE,card,USD,a31e637b-ae33-481d-b882-99bcd2a4bdfc,805f5cec-0609-450a-a601-6f36a57e794b,None,None,None,None,None,CHECKOUTDOTCOM,None,None,Sao Paulo,,BR,2022-05-01 00:00:51.590,2022-05-01 00:07:03.805,BLOCKED
24,faf456a6-9fa9-4b0f-89c0-533fd8d4456b,BENEFICIARY,CARDPROVIDER,NONE,card,USD,1da29d6d-af2f-4a0b-ae9a-7f43ca6a8c77,3422886a-ba5f-4c3e-ba45-7f58f79b60a8,mastercard,550209,NU PAGAMENTOS SA,BR,credit,STRIPE,None,None,Lago Do Itaenga,,BR,2022-05-01 00:01:13.839,2022-05-01 00:01:19.465,BLOCKED
19,8f3c1a2d-9c89-440f-9b97-870f5284b472,BENEFICIARY,CARDPROVIDER,NONE,card,USD,14637826-6be5-4fa0-bb43-b9fef10b054c,45f6aef4-cc54-4373-876d-ae735bd0d7cd,None,None,None,None,None,CHECKOUTDOTCOM,None,None,Dallas,US-TX,US,2022-05-01 00:03:06.627,2022-05-01 00:07:03.660,BLOCKED
46,9cc4f4f2-b027-439e-8880-56061a2bb6ac,BENEFICIARY,CARDPROVIDER,NONE,card,USD,678822b9-06f8-4c34-b967-5008ae2b10a0,3852653a-5629-449f-914a-77b31c93ea6e,visa,449210,ALASKA USA FEDERAL CREDIT UNION,US,debit,STRIPE,None,None,anchorage,US-AK,US,2022-05-01 00:04:02.401,2022-05-01 00:04:07.837,ACTIVE

In [154]:
payments_account_df.card_acquirer_name.unique()

array([None, 'STRIPE', 'CHECKOUTDOTCOM'], dtype=object)

In [153]:
payments_account_df[(payments_account_df.partner=='BLOCKCHAIN')&(payments_account_df.card_type.isnull())].head(10)

,id,type,partner,product,account_ref,currency,agent_ref,user_id,card_type,card_bin,card_issuer,card_issuer_country,card_funding_source,card_acquirer_name,ach_bankname,ach_bankaccounttype,billing_city,billing_state,billing_country,inserted_at,updated_at,last_state
6018,ac5b8981-6a84-4ba7-9b2d-cd86ce575770,VIRTUAL_REFERENCE,BLOCKCHAIN,SAVINGS,manual:68ab0368-673c-4363-8797-5be8cc0862ae,BTC,SAVINGS,68ab0368-673c-4363-8797-5be8cc0862ae,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:04:55.368,2022-05-01 23:04:55.368,ACTIVE
6184,4a8d58ad-13c8-43fe-83c2-ccac177085b8,VIRTUAL_REFERENCE,BLOCKCHAIN,SAVINGS,manual:77e0a64e-4363-45db-b2ec-ebcfc25267a5,USDT,SAVINGS,77e0a64e-4363-45db-b2ec-ebcfc25267a5,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:07:14.031,2022-05-01 23:07:14.031,ACTIVE
6261,b16f8420-4028-4138-8764-d3cc9780c61d,VIRTUAL_REFERENCE,BLOCKCHAIN,SIMPLEBUY,manual:31653218-b8f9-4b2c-933f-70b480ab192b,BCH,SIMPLEBUY,31653218-b8f9-4b2c-933f-70b480ab192b,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:11:52.539,2022-05-01 23:11:52.539,ACTIVE
6262,df9a22bb-6de5-4b06-a3df-40e122a30f79,VIRTUAL_REFERENCE,BLOCKCHAIN,SAVINGS,manual:31653218-b8f9-4b2c-933f-70b480ab192b,BTC,SAVINGS,31653218-b8f9-4b2c-933f-70b480ab192b,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:12:38.495,2022-05-01 23:12:38.495,ACTIVE
6918,1d5b5491-dfa2-415e-8f16-6059ec80a5e8,VIRTUAL_REFERENCE,BLOCKCHAIN,SIMPLEBUY,manual:5739dcc6-bd71-4bf2-adab-0d174c8ffc41,BTC,SIMPLEBUY,5739dcc6-bd71-4bf2-adab-0d174c8ffc41,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:34:04.902,2022-05-01 23:34:04.902,ACTIVE
7110,2f7c0c72-1bf7-4148-8e3d-aeac2e81ed88,VIRTUAL_REFERENCE,BLOCKCHAIN,SIMPLEBUY,manual:d5d60d84-96da-44e2-8f84-f735c60db058,BTC,SIMPLEBUY,d5d60d84-96da-44e2-8f84-f735c60db058,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:40:36.940,2022-05-01 23:40:36.940,ACTIVE
7663,a3d005f2-d6fb-4291-b94b-fcb56b5b7a6f,VIRTUAL_REFERENCE,BLOCKCHAIN,SIMPLEBUY,manual:3462b92b-dc42-4e74-85cc-932acb6e3d97,BTC,SIMPLEBUY,3462b92b-dc42-4e74-85cc-932acb6e3d97,None,None,None,None,None,None,None,None,None,None,None,2022-05-01 23:56:34.943,2022-05-01 23:56:34.943,ACTIVE

## Fetch MetaData providing Source and Schema of interest

In [126]:
from db_schemas.schema_utils import get_metadata_from_source_name, get_engine_from_source_name, SourceType

In [127]:
source_name, source_type = "nabu-payments", SourceType.POSTGRES

In [128]:
engine = get_engine_from_source_name(source_name, source_type)

In [136]:
engine

Engine(postgresql+psycopg2://etl:***@10.132.0.112:10069/nabu-payments)

### `get_metadata_from_source_name`

In [130]:
metadata = get_metadata_from_source_name(source_name, schema="payments", use_pickle=True)

In [131]:
metadata.reflect(bind=engine, views=True)

In [132]:
metadata.tables["payments.account"]

Table('account', MetaData(bind=None), Column('id', UUID(), table=<account>, primary_key=True, nullable=False), Column('type', TEXT(), table=<account>, nullable=False), Column('partner', TEXT(), table=<account>, nullable=False), Column('product', TEXT(), table=<account>, nullable=False), Column('account_ref', TEXT(), table=<account>, nullable=False), Column('currency', TEXT(), table=<account>, nullable=False), Column('agent_ref', TEXT(), table=<account>), Column('extra_attributes', JSONB(astext_type=Text()), table=<account>), Column('user', UUID(), table=<account>), Column('inserted_at', TIMESTAMP(), table=<account>, nullable=False), Column('updated_at', TIMESTAMP(), table=<account>, nullable=False), Column('last_state', TEXT(), table=<account>), schema='payments')

## DS_DB_MAPPING

In [4]:
from customers_analytics.nabu.data_processing.nabu_db import DS_DB_MAPPING, DsDatabases

/home/aektov/.local/share/virtualenvs/python-data-science-mirror-JM_PQ88B/lib/python3.8/site-packages/arctic/_util.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
/home/aektov/.local/share/virtualenvs/python-data-science-mirror-JM_PQ88B/lib/python3.8/site-packages/arctic/store/_pandas_ndarray_store.py:6: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import DataFrame, Series, Panel

In [5]:
from db_schemas.schema_utils import get_class_by_table_name
from db_schemas.dbs.nabu_gateway_internal import NabuInternalBase, NabuPaymentsProdMixin, PaymentsAccount
from db_schemas.base_classes import InternalTable

In [6]:
destination_db = DsDatabases.GATEWAY

In [7]:
ds_db_info = DS_DB_MAPPING[destination_db]
internal_base_class = ds_db_info.internal_base_class
client = ds_db_info.internal_client_func()

In [21]:
client

## Get Internal Class for specified tbl name

### `get_class_by_table_name`

In [8]:
#Given a base declarative class and a table name, it returns the corresponding class

table_name = "payments_account"

internal_class = get_class_by_table_name(internal_base_class, table_name)

In [9]:
internal_class

db_schemas.dbs.nabu_gateway_internal.PaymentsAccount

## Method to get the list of columns names of the columns existing in prod

In [138]:
meta = PaymentsAccount.src_metadata()

In [139]:
metadata.reflect(bind=engine, views=True)

In [140]:
metadata.tables[PaymentsAccount.prod_table]

Table('account', MetaData(bind=None), Column('id', UUID(), table=<account>, primary_key=True, nullable=False), Column('type', TEXT(), table=<account>, nullable=False), Column('partner', TEXT(), table=<account>, nullable=False), Column('product', TEXT(), table=<account>, nullable=False), Column('account_ref', TEXT(), table=<account>, nullable=False), Column('currency', TEXT(), table=<account>, nullable=False), Column('agent_ref', TEXT(), table=<account>), Column('extra_attributes', JSONB(astext_type=Text()), table=<account>), Column('user', UUID(), table=<account>), Column('inserted_at', TIMESTAMP(), table=<account>, nullable=False), Column('updated_at', TIMESTAMP(), table=<account>, nullable=False), Column('last_state', TEXT(), table=<account>), schema='payments')

In [142]:
PaymentsAccount.prod_table

'payments.account'

In [141]:
metadata.tables[PaymentsAccount.prod_table].indexes

{Index('account_account_ref_agent_ref_type_idx', Column('account_ref', TEXT(), table=<account>, nullable=False), Column('agent_ref', TEXT(), table=<account>), Column('type', TEXT(), table=<account>, nullable=False), unique=True),
 Index('account_currency_idx', Column('currency', TEXT(), table=<account>, nullable=False)),
 Index('account_last_state_idx', Column('last_state', TEXT(), table=<account>)),
 Index('account_partner_idx', Column('partner', TEXT(), table=<account>, nullable=False)),
 Index('account_product_idx', Column('product', TEXT(), table=<account>, nullable=False)),
 Index('account_type_idx', Column('type', TEXT(), table=<account>, nullable=False)),
 Index('account_type_partner_last_state_idx', Column('type', TEXT(), table=<account>, nullable=False), Column('partner', TEXT(), table=<account>, nullable=False), Column('last_state', TEXT(), table=<account>)),
 Index('account_updated_at_idx', Column('updated_at', TIMESTAMP(), table=<account>, nullable=False)),
 Index('account_user_idx', Column('user', UUID(), table=<account>))}

In [143]:
PaymentsAccount.columns_from_prod()

['account_ref',
 'agent_ref',
 'currency',
 'id',
 'inserted_at',
 'last_state',
 'partner',
 'product',
 'type',
 'updated_at',
 'user']

## Get Schema Infomation

In [2]:
from db_schemas.base_classes import convert_camel_case_to_underscore

In [3]:
client_internal = get_nabu_client_internal()
tbl_name = convert_camel_case_to_underscore('PaymentsAccount')

WARNING:root:acton source, blob not OK
WARNING:root:iterable-dev source, api_key not OK
WARNING:root:web3-api-infura source, token not OK

In [4]:
__TBLCLSNAME__ = 'PaymentsAccount'
internal_tbl_name = convert_camel_case_to_underscore(__TBLCLSNAME__)

meta_query=\
'''
SELECT 
   column_name, 
   data_type,
   character_maximum_length
FROM 
   information_schema.columns
WHERE 
   table_name = '{}'
'''.format(internal_tbl_name)

df_meta = client_internal.dataframe_from_query(meta_query)

In [5]:
df_meta

,column_name,data_type,character_maximum_length
0,id,uuid,NaN
1,type,character varying,50.0
2,partner,character varying,50.0
3,product,character varying,30.0
4,account_ref,character varying,300.0
5,currency,character varying,30.0
6,agent_ref,character varying,300.0
7,user,uuid,NaN
8,inserted_at,timestamp without time zone,NaN
9,updated_at,timestamp without time zone,NaN
10,last_state,character varying,20.0
11,ach_bank_account_type,character varying,20.0
12,ach_bank_name,character varying,200.0
13,billing_city,character varying,100.0
14,billing_country,character varying,20.0
15,card_acquirer_name,character varying,50.0
16,card_bin,integer,NaN
17,card_funding_source,character varying,50.0
18,card_issuer,character varying,100.0
19,card_issuer_country,character varying,20.0
20,card_type,character varying,30.0
21,user_id,uuid,NaN

## Get Indexes Information for specified tbl

In [6]:
meta_query = \
'''
SELECT
    tablename,
    indexname,
    indexdef
FROM
    pg_indexes
WHERE
    tablename = '{}'
    -- schemaname = 'public'
-- ORDER BY
    -- tablename,
    -- indexname;
'''.format(internal_tbl_name)

df_meta = client_internal.dataframe_from_query(meta_query)

df_meta

,tablename,indexname,indexdef
0,payments_account,payments_account__pk,CREATE UNIQUE INDEX payments_account__pk ON pu...
1,payments_account,account_account_ref_agent_ref_type_idx,CREATE INDEX account_account_ref_agent_ref_typ...
2,payments_account,account_currency_idx,CREATE INDEX account_currency_idx ON public.pa...
3,payments_account,account_last_state_idx,CREATE INDEX account_last_state_idx ON public....
4,payments_account,account_partner_idx,CREATE INDEX account_partner_idx ON public.pay...
5,payments_account,account_product_idx,CREATE INDEX account_product_idx ON public.pay...
6,payments_account,account_type_idx,CREATE INDEX account_type_idx ON public.paymen...
7,payments_account,account_type_partner_last_state_idx,CREATE INDEX account_type_partner_last_state_i...
8,payments_account,account_updated_at_idx,CREATE INDEX account_updated_at_idx ON public....
9,payments_account,account_user_idx,CREATE INDEX account_user_idx ON public.paymen...
10,payments_account,payments_account_account_ref_idx,CREATE INDEX payments_account_account_ref_idx ...
11,payments_account,payments_account_ach_bank_account_type_idx,CREATE INDEX payments_account_ach_bank_account...
12,payments_account,payments_account_ach_bank_name_idx,CREATE INDEX payments_account_ach_bank_name_id...
13,payments_account,payments_account_billing_city_idx,CREATE INDEX payments_account_billing_city_idx...
14,payments_account,payments_account_billing_country_idx,CREATE INDEX payments_account_billing_country_...
15,payments_account,payments_account_card_acquirer_name_idx,CREATE INDEX payments_account_card_acquirer_na...
16,payments_account,payments_account_card_bin_idx,CREATE INDEX payments_account_card_bin_idx ON ...
17,payments_account,payments_account_card_funding_source_idx,CREATE INDEX payments_account_card_funding_sou...
18,payments_account,payments_account_card_issuer_country_idx,CREATE INDEX payments_account_card_issuer_coun...
19,payments_account,payments_account_card_type_idx,CREATE INDEX payments_account_card_type_idx ON...

## Get SQL-Query str given on the input client and internal tbl class

In [29]:
source_client = get_nabu_payments_client()

### `_get_query_from_table`

In [27]:
from db_schemas.data_processing.get_upsert_data import _get_query_from_table

In [30]:
#Function to get the query to load data from a table within a time range

start_dt, end_dt = datetime(2021,1,1,0,0), datetime(2021,10,1,0,0)

query = _get_query_from_table(
    source_client, internal_class, start_dt, end_dt
)

In [31]:
print(query)

select account_ref, agent_ref, currency, id, inserted_at, last_state, partner, product, type, updated_at, "user" from payments.account where (inserted_at between '2021-01-01 00:00:00' and '2021-10-01 00:00:00' or updated_at between '2021-01-01 00:00:00' and '2021-10-01 00:00:00')

# Applying `run_select` method to fetch data from nabu-gateway

In [32]:
client_internal = get_nabu_client_internal()
start_dt, end_dt = datetime(2022,1,1,0,0), datetime(2022,4,1,0,0)

df_clout = run_select(
    client=client_internal,
    table='ach_failures',
    in_clauses={"nacha_code": (['R03', 'R08', 'R16'], True)},
    null_clauses={"usd_balance": False},
    #between_clauses={"inserted_at": (start_dt, end_dt)},
    greater_less_clauses={'inserted_at': (datetime(2022, 2, 1, 0, 0), True)}
)

In [33]:
df_clout.head(10)

,payment_id,insufficient_balance,nacha_code,amount,inserted_at,bank_balance,available_bank_balance,balance_last_updated,product,instant_settlement,usd_balance,user_id,withdrawal_lock_expires_at,current_state,preoriginated_failure_error
0,33b420dc-bba5-4f27-b607-fc513b84ff5f,False,R03,6000.0,2022-03-18 16:32:37.029,7500.00,7500.00,2022-03-18 16:14:24,SIMPLEBUY,False,-12.644875,46a9c977-3968-4937-a937-d20f503f116a,NaT,REJECTED,None
1,14abb357-9ced-49e4-8728-c892136d7f7f,False,R03,500.0,2022-03-18 16:16:59.161,7500.00,7500.00,2022-03-18 16:14:24,SIMPLEBUY,True,-12.644875,46a9c977-3968-4937-a937-d20f503f116a,2032-03-18 23:58:26.236,REFUNDED,None
2,1e727ca8-b6a1-4bd9-b404-8b069db0dbea,False,R03,500.0,2022-03-18 16:17:45.282,7500.00,7500.00,2022-03-18 16:14:24,SIMPLEBUY,False,-12.644875,46a9c977-3968-4937-a937-d20f503f116a,NaT,REJECTED,None
3,3d267142-01f6-4748-8722-b03944194dcb,False,R16,10.0,2022-03-17 23:49:21.740,25.00,25.00,2022-03-12 01:14:28,SIMPLEBUY,False,1488.852739,e9a7ac9f-4359-4454-b331-1989003ecd72,NaT,REJECTED,None
4,8023242c-6dab-443c-a478-c34494e0be02,False,R03,100.0,2022-03-18 04:38:49.692,306.68,306.68,2022-01-15 13:44:37,SIMPLEBUY,False,1.640329,74cd3ad3-3310-4bce-8305-ee89402c0ed9,NaT,REJECTED,None
5,aa187df1-848d-4fb9-891b-ee67c7ad19ba,False,R16,14500.0,2022-03-17 08:17:12.561,19000.00,19000.00,2022-03-18 10:43:22,SIMPLEBUY,False,24183.225338,e9df3416-2317-436b-82e9-069782c3f46a,2032-03-18 23:58:22.860,REFUNDED,None
6,f5e84468-67eb-48d6-b358-c55869b2b896,False,R16,25000.0,2022-03-16 17:34:36.036,65000.00,65000.00,2022-03-17 18:37:48,SIMPLEBUY,False,25634.675649,9a432418-1076-494a-b955-3e900876a08c,2032-03-18 23:58:22.447,REFUNDED,None
7,a10f4dc4-2a96-4a1d-9450-d6e75e0e809e,False,R16,25000.0,2022-03-16 17:35:24.705,65000.00,65000.00,2022-03-17 18:37:48,SIMPLEBUY,False,25634.675649,9a432418-1076-494a-b955-3e900876a08c,2032-03-18 23:58:22.508,REFUNDED,None
8,6cb8c84c-e069-46ec-91ab-d8878a12a2e8,False,R16,25000.0,2022-03-16 17:23:05.039,70000.00,70000.00,2022-03-17 22:00:00,SIMPLEBUY,False,23894.786081,b7da45e7-657d-4ff5-a6ef-72935e9cf230,2032-03-18 23:58:22.641,REFUNDED,None
9,607bad00-d0f3-4828-bd4d-2df489bbc1d7,False,R16,25000.0,2022-03-16 17:27:54.319,70000.00,70000.00,2022-03-17 22:00:00,SIMPLEBUY,False,23894.786081,b7da45e7-657d-4ff5-a6ef-72935e9cf230,2032-03-18 23:58:22.759,REFUNDED,None

## Working with `exchange_rate_*` tbls

### `get_exchange_rate` - This function gets exchange rate for the given base currencies.

In [41]:
from customers_analytics.nabu.nabu_db_utils import get_exchange_rate

update_dt = datetime(2022, 5, 5)
time_range = (datetime(2018, 1, 1), update_dt)

client = get_nabu_ledger_client()

query="select distinct currency from ledger.balance_snapshot"
df = client.dataframe_from_query(query)

coins = list(df["currency"].unique())

client = get_nabu_client()
exchange_rates = get_exchange_rate(client=client, base_ccy=coins, time_range=time_range)
exchange_rates.rename(
    columns={"value": "price", "base_ccy": "currency", "inserted_at": "created_at"},
    inplace=True,
)

In [60]:
exchange_rates.head()

,currency,price,exchange_rate_scale,currency_version_scale,increment,created_at
0,CAD,76,2,2.0,1.0,2019-02-04 13:34:44.817
3,CHF,99,2,2.0,1.0,2019-02-04 13:34:44.832
6,GBP,130,2,2.0,1.0,2019-02-04 13:34:44.949
9,USD,100,2,2.0,1.0,2019-02-04 13:34:44.967
12,SEK,11,2,2.0,1.0,2019-02-04 13:34:44.980

In [61]:
exchange_rates[exchange_rates.price.isnull()]

Empty DataFrame
Columns: [currency, price, exchange_rate_scale, currency_version_scale, increment, created_at]
Index: []

# Query data from Postgreas via `dataframe_from_query` build-in method

In [17]:
client_internal = get_nabu_client_internal()

In [18]:
client_internal.client

In [19]:
query= \
'''
with stripe as (
select distinct
    to_char(date_trunc('month', created_at), 'yyyy-MM-dd') created_at
    --to_char(created_at, 'yyyy-MM-dd') as created_at
    ,case 
     when lower(card_type) like '%master%' then 'mastercard'
     when lower(card_type) like '%visa%' then 'visa'
     else 'other'
     end card_type
    ,payment_reference
    ,cast(is_fraud as int) is_fraud
from card_payments_fraud_stats
where
    lower(processor) like '%stripe%'
    --and is_fraud = false
    and created_at > '2021-12-01'
    --and lower(card_type) like '%visa%'
    --and acquirer like '%stripe%'
) 
select
     created_at
    ,card_type
    -- ,is_fraud
    ,count(is_fraud) as total_cnt
    ,sum(is_fraud) fraud_cnt
from stripe
group by created_at, card_type
order by 1, 3 desc
'''

df = client_internal.dataframe_from_query(query)

In [21]:
df.head(10)

   created_at   card_type  total_cnt  fraud_cnt
0  2021-12-01        visa        203          0
1  2021-12-01  mastercard        130          0
2  2022-01-01        visa       4743         16
3  2022-01-01  mastercard       3263          1
4  2022-02-01        visa       7477         18
5  2022-02-01  mastercard       4259          0
6  2022-03-01        visa      11000         55
7  2022-03-01  mastercard       5532          0
8  2022-03-01       other          9          0
9  2022-04-01        visa       8690         44

In [23]:
# user_id = '0b05ac8d-8c40-4d04-81ca-3859a4976c2e'
client_internal = get_nabu_client_internal()

In [7]:
query = \
'''
with stripe as (
select distinct
    to_char(date_trunc('month', created_at), 'yyyy-MM-dd') created_at
    --to_char(created_at, 'yyyy-MM-dd') as created_at
    ,case 
     when lower(card_type) like '%master%' then 'mastercard'
     when lower(card_type) like '%visa%' then 'visa'
     else 'other'
     end card_type
    ,payment_reference
    ,cast(is_fraud as int) is_fraud
from card_payments_fraud_stats
where
    lower(processor) like '%checkout%'
    --and is_fraud = false
    and created_at > '2021-12-01'
    --and lower(card_type) like '%visa%'
    --and acquirer like '%stripe%'
) 
select
     created_at
    ,card_type
    -- ,is_fraud
    ,count(is_fraud) as total_cnt
    ,sum(is_fraud) fraud_cnt
from stripe
group by created_at, card_type
having lower(card_type) like '%master%'
order by 1, 3 desc
'''

df = client_internal.dataframe_from_query(query)

In [8]:
df.head(20)

   created_at   card_type  total_cnt  fraud_cnt
0  2021-12-01  mastercard        500          0
1  2022-01-01  mastercard       5411          0
2  2022-02-01  mastercard       5482          0
3  2022-03-01  mastercard       8665          0
4  2022-04-01  mastercard       9669          0

## Client External

In [48]:
client_payment = role.sources["nabu-payments"].create_client()

## `payments.account` cross join `payments.transaction`

In [45]:
query=\
'''
with funding_source as (
select 
    account.extra_attributes -> 'card' ->> 'bin' as card_bin,
    account.extra_attributes -> 'card' ->> 'issuer' as card_issuer,
    account.extra_attributes -> 'card' ->> 'funding_source' as card_funding_source,
    account.extra_attributes -> 'card' ->> 'issuer_country' as card_issuer_country,
    account.extra_attributes ->> 'card_acquirer_name' as card_acquirer_name    
from payments.account, payments.transaction
where transaction.beneficiary = account.id 
and account.extra_attributes -> 'card' ->> 'issuer_country' = 'US'
and account.extra_attributes -> 'card' ->> 'funding_source' is not null
and account.partner in ('EVERYPAY', 'CARDPROVIDER')
and transaction.created_at >= '2022-04-01T00:00:00+00:00'
)
select 
    *
from funding_source

--select 
--    lower(funding_source), count(*) as cnt 
--from funding_source
--group by lower(funding_source)
'''

In [46]:
df = client_payment.dataframe_from_query(query)

In [47]:
df.head(15)

,card_bin,card_issuer,card_funding_source,card_issuer_country,card_acquirer_name
0,551010,EGLIN FEDERAL CREDIT UNION,debit,US,STRIPE
1,416085,MECHANICS BANK,debit,US,STRIPE
2,416085,MECHANICS BANK,debit,US,STRIPE
3,423829,MICHIGAN SCHOOLS AND GOVERNMENT CREDIT UNION,debit,US,CHECKOUTDOTCOM
4,423829,MICHIGAN SCHOOLS AND GOVERNMENT CREDIT UNION,debit,US,CHECKOUTDOTCOM
5,447914,TIB THE INDEPENDENT BANKERSBANK,debit,US,STRIPE
6,400022,NAVY FEDERAL CREDIT UNION,debit,US,CHECKOUTDOTCOM
7,400022,NAVY FEDERAL CREDIT UNION,debit,US,CHECKOUTDOTCOM
8,434256,WELLS FARGO BANK NATIONAL ASSOCIATION,debit,US,STRIPE
9,434256,WELLS FARGO BANK NATIONAL ASSOCIATION,debit,US,STRIPE
10,510404,"METABANK, NATIONAL ASSOCIATION",debit,US,STRIPE
11,531260,"BANK OF AMERICA, NATIONAL ASSOCIATION",debit,US,STRIPE
12,510805,"CAPITAL ONE BANK (USA), NATIONAL ASSOCIATION",debit,US,None
13,421783,STRIDE BANK NATIONAL ASSOCIATION,credit,US,STRIPE
14,510404,"METABANK, NATIONAL ASSOCIATION",debit,US,STRIPE

## `payments.account`

In [ ]:
cols=[
    "payments.account.id",
    "payments.account.type",
    "payments.account.partner",
    "payments.account.product",
    "payments.account.account_ref",
    "payments.account.currency",
    "payments.account.agent_ref",
    # "payments.account.extra_attributes",
    "payments.account.user",
    "payments.account.inserted_at",
    "payments.account.updated_at",
    "payments.account.last_state",
]

In [89]:
query=\
'''
select
 payments.account.id
,payments.account.type
,payments.account.partner
,payments.account.product
,payments.account.account_ref
,payments.account.currency
,payments.account.agent_ref
,payments.account.user
,payments.account.inserted_at
,payments.account.updated_at
,payments.account.last_state
from payments.account
where inserted_at between '2019-11-01T00:00:00+00:00' and '2019-11-01T05:00:00+00:00'
'''

In [90]:
df = client_payment.dataframe_from_query(query)

In [96]:
df.head()

,id,type,partner,product,account_ref,currency,agent_ref,user,inserted_at,updated_at,last_state
0,6f2c295b-9df1-43ef-9794-f07dfd5cd281,VIRTUAL_REFERENCE,SILVERGATE,MERCURY,HRH0LP2A,USD,5090015388,02d17733-27ef-46eb-9f0b-f25040b13f2e,2019-11-01 01:13:57.917,2019-11-01 01:13:57.917,BLOCKED
1,6f30d944-aa99-4d05-8798-34dd00238960,VIRTUAL_REFERENCE,SILVERGATE,MERCURY,A2R774UZ,USD,5090015388,4b3b460f-30d5-45db-bd0f-465df4412e3e,2019-11-01 00:20:03.877,2019-11-01 00:20:03.877,BLOCKED
2,8d467ea0-493d-4384-9d4c-e28f5afb1e94,VIRTUAL_REFERENCE,SILVERGATE,MERCURY,Y4B21M18,USD,5090015388,91cbc4ee-2e00-4c40-a016-37abf46835c0,2019-11-01 02:54:32.068,2019-11-01 02:54:32.068,BLOCKED
3,05a12ff4-0836-41f7-b381-12c15640cf5d,VIRTUAL_REFERENCE,HWS,MERCURY,3CEzs3BDYwhffMuaX7fatc2u7f9oiAQSJy,BTC,None,e2464cba-693d-4022-acae-3f12c7dc4a05,2019-11-01 03:39:34.956,2019-11-01 03:39:34.956,ACTIVE
4,0a32d01e-db4e-4128-bc8a-81a4806b2884,VIRTUAL_REFERENCE,HWS,MERCURY,34dS6QbLg9raRf74baTNfSboTb5JewwFiQ,BTC,None,1ef737a8-0cd9-4ba4-8344-d689cc1f37a5,2019-11-01 00:30:05.205,2019-11-01 00:30:05.205,ACTIVE

## `payments.account`, `payments.transaction_state`, `payments.transaction`

In [6]:
query=\
'''
with trnx_avatar as (
select
         payments.transaction.id as transaction_id
        ,payments.transaction.extra_attributes -> 'cardProvider' ->> 'order_reference' as order_reference
        ,payments.transaction.extra_attributes -> 'cardProvider' ->> 'payment_reference' as payment_reference
        ,payments.account.user as user_id
        ,payments.account.partner as partner
        ,payments.account.extra_attributes ->> 'name' as card_name
        ,payments.account.extra_attributes ->> 'type' as card_type
        ,payments.account.extra_attributes ->> 'mobile_payment' as mobile_payment
        ,payments.transaction_leg.usd_amount as usd_amount
        ,payments.transaction_state.state
        ,payments.transaction_state.extra_attributes ->> 'debit' as debit
        ,payments.transaction_state.extra_attributes ->> 'credit' as credit
        ,payments.transaction.extra_attributes ->> 'recharge_state' is not null as is_recharge
        ,payments.transaction.extra_attributes ->> 'userTier' as tier
        ,payments.transaction.external_ref as simple_buy_id        
        ,payments.account.extra_attributes ->> 'email' as email
        ,payments.account.extra_attributes ->> 'card_acquirer_name' as card_acquirer_name 
        ,payments.account.extra_attributes -> 'billing_address' ->> 'city' as city
        ,payments.account.extra_attributes -> 'billing_address' ->> 'state' as state
        ,payments.account.extra_attributes -> 'billing_address' ->> 'country' as country 
        ,payments.account.extra_attributes -> 'billing_address' ->> 'postCode' as postCode
        ,payments.account.extra_attributes -> 'billing_address' ->> trim(concat('line1', ' ', 'line2')) as address
        ,payments.transaction.created_at
        ,payments.transaction_state.inserted_at
        ,payments.account.extra_attributes as card__extra_attributes
        ,payments.transaction_state.extra_attributes as transaction_state_attributes
        ,payments.transaction.extra_attributes as transaction_extra_attributes        
from payments.transaction
left join payments.transaction_state on payments.transaction.id=payments.transaction_state.transaction
left join payments.account on payments.account.id=payments.transaction.beneficiary
left join payments.transaction_leg on payments.transaction_leg.id=payments.transaction.id
where 1 = 1
    --and payments.account.extra_attributes -> 'name' is null
    and payments.account.account_ref = 'card'
    and payments.transaction_state.state = 'COMPLETE'
    and payments.transaction_leg.type = 'PRINCIPAL'
    and payments.account.partner in ('CARDPROVIDER', 'EVERYPAY')
    -- and payments.account.partner in ('CARDPROVIDER', 'EVERYPAY', 'SIGNATURE', 'LHV', 'YAPILY', 'YODLEE', 'SILVERGATE') 
    and payments.transaction_state.inserted_at between '2022-04-01T00:00:00+00:00' and '2022-04-25T00:00:00+00:00'
)
select * from trnx_avatar
--where trnx_avatar.payment_reference in ('pay_e3tdu35cl73enldmspca3bh3i4', 'pay_gbnoe6ttulcuzmkznbu6w72nwe')
'''

In [7]:
df = client_payment.dataframe_from_query(query)

In [8]:
df.head(50)

,transaction_id,order_reference,payment_reference,user_id,partner,card_name,card_type,mobile_payment,usd_amount,state,debit,credit,is_recharge,tier,simple_buy_id,email,card_acquirer_name,city,state,country,postcode,address,created_at,inserted_at,card__extra_attributes,transaction_state_attributes,transaction_extra_attributes
0,b70bcb70-d5f5-4cce-9624-a61b907e0781,sp::b70bcb70-d5f5-4cce-9624-a61b907e0781,pay_ohdrvyrjy7yudcdkppvbgylewm,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,500.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,373cf27a-6602-4441-8add-affac70c5f15,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-01 02:15:12.737,2022-04-01 02:15:23.357798,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
1,6d8a3ae8-63d7-4dd3-92a4-2c1f389e2aea,sp::6d8a3ae8-63d7-4dd3-92a4-2c1f389e2aea,pay_eh7daae5cscu7eh6ot6hv37i5a,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,500.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,f64536b4-6399-42b4-b618-116d633bec7c,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-01 13:58:53.084,2022-04-01 13:59:00.082749,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
2,f28fa3ea-50e1-4b4b-b30a-a9c8568ca1c1,sp::f28fa3ea-50e1-4b4b-b30a-a9c8568ca1c1,pi_3KjqeIKDv3vdWtQB0EzQashG,18f64623-b04a-4d03-837f-1231c45aa264,CARDPROVIDER,MUKTAR HOSSAIN,PAYMENT_CARD,None,1053.120000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,557e93a0-9542-43e4-9216-84c8c4b8d7ba,muktar.vu.edu@gmail.com,STRIPE,Naogaon,,BD,6230,None,2022-04-01 20:00:45.143,2022-04-01 20:00:56.678294,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
3,94d6ea15-587f-43db-9077-823ba0a7ad7f,sp::94d6ea15-587f-43db-9077-823ba0a7ad7f,pi_3KjqjJKDv3vdWtQB1vOXNIRk,18f64623-b04a-4d03-837f-1231c45aa264,CARDPROVIDER,MUKTAR HOSSAIN,PAYMENT_CARD,None,1050.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,9e66ac8e-0f18-46a9-b9a8-34bed8b857b1,muktar.vu.edu@gmail.com,STRIPE,Naogaon,,BD,6230,None,2022-04-01 20:05:56.434,2022-04-01 20:06:06.841100,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
4,b2bc4b5e-c5ea-43bb-a27f-5eba257d745e,sp::b2bc4b5e-c5ea-43bb-a27f-5eba257d745e,pi_3KjqneKDv3vdWtQB16bpDpaT,18f64623-b04a-4d03-837f-1231c45aa264,CARDPROVIDER,MUKTAR HOSSAIN,PAYMENT_CARD,None,244.340000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,c3d784a2-5172-432e-a654-639e4f44dcdb,muktar.vu.edu@gmail.com,STRIPE,Naogaon,,BD,6230,None,2022-04-01 20:10:25.338,2022-04-01 20:10:36.366227,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
5,9a224ea9-9952-43f2-82fd-f70092dcfddc,sp::9a224ea9-9952-43f2-82fd-f70092dcfddc,pi_3KjrGpKDv3vdWtQB0SmPIIIm,18f64623-b04a-4d03-837f-1231c45aa264,CARDPROVIDER,MUKTAR HOSSAIN,PAYMENT_CARD,None,1024.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,05b69859-f089-4890-801c-76616396f3c8,muktar.vu.edu@gmail.com,STRIPE,Naogaon,,BD,6230,None,2022-04-01 20:40:34.491,2022-04-01 20:40:44.616895,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
6,9d499bbb-d008-43f5-9513-b9af534ac2b7,sp::9d499bbb-d008-43f5-9513-b9af534ac2b7,pay_skd3ugwx63xezp466sdtvv2zqy,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,500.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,91bca874-7863-408a-9ae3-1240bb1160f5,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-02 11:25:12.414,2022-04-02 11:25:19.563156,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
7,ad8a523c-d31d-498b-a13f-523f489f7ace,sp::ad8a523c-d31d-498b-a13f-523f489f7ace,pi_3KkdiiKDv3vdWtQB0tTvZjlU,eb93e725-03ac-41e9-abe1-fe3d17a0771a,CARDPROVIDER,Victor Lameck,PAYMENT_CARD,None,1200.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,67e8b246-462b-4bf2-8da5-5ce4286b7b7f,vshifuna@gmail.com,STRIPE,Nairobi,,KE,00100,None,2022-04-04 00:24:35.437,2022-04-04 00:24:45.735734,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
8,dfdae393-4a1c-412e-b4f1-2af68fd9614b,sp::dfdae393-4a1c-412e-b4f1-2af68fd9614b,pi_3KkdjtKDv3vdWtQB0SUUmG26,eb93e725-03ac-41e9-abe1-fe3d17a0771a,CARDPROVIDER,Victor Lameck,PAYMENT_CARD,None,125.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,c0ace6a0-00d5-4a49-ad5f-6e3ad155210e,vshifuna@gmail.com,STRIPE,Nairobi,,KE,00100,None,2022-04-04 00:25:48.780,2022-04-04 00:25:58.484652,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
9,97711efd-aed3-4eba-869d-4be656f80db3,sp::97711efd-aed3-4eba-869d-4be656f80db3,pi_3Kkdj8KDv3vdWtQB1sNjulGB,eb93e725-03ac-41e9-abe1-fe3d17a0771a,CARDPROVIDER,Victor Lameck,PAYMENT_CARD,None,1200.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,8d342be6-eb70-4754-bc02-57d0246590c4,vshifuna@gmail.com,STRIPE,Nairobi,,KE,00100,None,2022-04-04 00:25:01.532,2022-04-04 00:25:10.922178,"{'card': {'bin': '555753', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
10,3b80aa5f-ffc2-4f01-a748-f775bc8c1016,sp::3b80aa5f-ffc2-4f01-a748-f775bc8c1016,pay_wrzqmnath6oubfqt6vzbhlf4na,9f37f9e5-3198-4c0a-9174-513ff45efbea,CARDPROVIDER,shannon boswell,PAYMENT_CARD,None,138.700000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,1040afa6-0525-48db-839a-0e5dcf66c6d7,liltilistmonkey@gmail.com,STRIPE,Auckland,,NZ,0612,None,2022-04-04 06:56:47.682,2022-04-04 06:57:00.409628,"{'card': {'bin': '483741', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
11,0c5966f7-c8c1-43b9-94bc-6d7696ab53b6,sp::0c5966f7-c8c1-43b9-94bc-6d7696ab53b6,pay_7ms54vysb3menll2toymog5tza,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,525.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,408a7ae2-c574-458c-b06a-ab4bd8867a57,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-04 15:30:46.887,2022-04-04 15:30:53.999512,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
12,eceb3deb-fdd3-43a6-befb-99277d6c5925,sp::eceb3deb-fdd3-43a6-befb-99277d6c5925,pay_z366yi6wkm6exaw23f6rdohhoy,832df285-10f7-4758-abab-50f994fb1d86,CARDPROVIDER,James Flores,PAYMENT_CARD,None,108.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,3b0b0c3a-efc7-449f-947f-91c6b59ddebb,j3m4s@hotmail.com,None,Fresno,CA,US,93728,None,2022-04-04 11:50:35.904,2022-04-04 11:51:06.577291,"{'card': {'bin': '510805', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
13,30f74e74-13a9-4995-aec7-ffaa6495759f,sp::30f74e74-13a9-4995-aec7-ffaa6495759f,pay_zaiuvmf2mivubj5ffnbazsdohe,6555d2c7-33cf-46ce-95eb-54055111be74,CARDPROVIDER,Sanil Jain,PAYMENT_CARD,None,7.324800000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,46f01c10-f903-4944-bb39-674bee6984e8,saniljain.sjain@gmail.com,STRIPE,Bath,,GB,BA2 7PS,None,2022-04-06 15:23:20.036,2022-04-06 15:23:43.156528,"{'card': {'bin': '535522', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'GBP':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
14,7b6202d7-fcd2-414b-9582-a1441b8cd32b,sp::7b6202d7-fcd2-414b-9582-a1441b8cd32b,pay_4n5vl55urg4u7hpv3er337do7y,a2caf044-e5f0-460f-955d-32de660ae4e4,CARDPROVIDER,Rabina Rai,PAYMENT_CARD,None,25.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,dc93cd13-927f-4fbf-a3a7-ff4d125c6dba,julne27@gmail.com,STRIPE,Hong Kong,,HK,na,None,2022-04-08 02:04:34.477,2022-04-08 02:05:05.622773,"{'card': {'bin': '448060', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
15,c3a6c526-faa7-4517-9452-f0960220e3c1,sp::c3a6c526-faa7-4517-9452-f0960220e3c1,pay_4gkqlxmkezsurf3fkuicxsbaji,a2caf044-e5f0-460f-955d-32de660ae4e4,CARDPROVIDER,Rabina Rai,PAYMENT_CARD,None,27.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,6064cd40-3d97-4cec-b9d9-32f199ccfa47,julne27@gmail.com,STRIPE,Hong Kong,,HK,na,None,2022-04-08 02:07:28.256,2022-04-08 02:07:43.112560,"{'card': {'bin': '448060', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
16,47c28025-b62b-45eb-b198-afb41db840bb,sp::47c28025-b62b-45eb-b198-afb41db840bb,pay_drvrow7djtwupl5oukt5oqch44,a2caf044-e5f0-460f-955d-32de660ae4e4,CARDPROVIDER,Rabina Rai,PAYMENT_CARD,None,20.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,2e556eb6-1062-49eb-a35f-b8d07ff02f9d,julne27@gmail.com,STRIPE,Hong Kong,,HK,na,None,2022-04-08 02:17:44.737,2022-04-08 02:18:05.420652,"{'card': {'bin': '448060', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
17,39e06097-f228-4aed-a314-9b0d5110eacf,sp::39e06097-f228-4aed-a314-9b0d5110eacf,pay_gr3fzmll4gsuvf5zddnbkvnff4,a2caf044-e5f0-460f-955d-32de660ae4e4,CARDPROVIDER,Rabina Rai,PAYMENT_CARD,None,30.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,d42aca98-cd9d-4a6d-b032-25f48c39243e,julne27@gmail.com,STRIPE,Hong Kong,,HK,na,None,2022-04-08 02:14:36.483,2022-04-08 02:14:52.380930,"{'card': {'bin': '448060', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
18,5ce51ea2-38de-4674-9af5-6107ec151e4e,sp::5ce51ea2-38de-4674-9af5-6107ec151e4e,pay_x4lwes5sydrupgwn5vonnrrgf4,146dafb5-16d0-4eef-aa72-cf1b9fba294c,CARDPROVIDER,Jose Rene Mendoza,PAYMENT_CARD,None,5.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,5aa7b380-6142-4176-a2ec-ea13d59c8be6,jose_mendoza191@outlook.com,STRIPE,Berlín,,SV,0615,None,2022-04-07 20:58:26.613,2022-04-07 20:58:36.369547,"{'card': {'bin': '489983', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
19,1354fb01-aef4-4fda-9d9a-f9c5dd0067d3,sp::1354fb01-aef4-4fda-9d9a-f9c5dd0067d3,pay_a6qfpn5ph2ou3mdjasyonke7ai,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,250.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,b772f27c-e2b5-49a5-9289-a661b209af90,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-07 20:54:27.577,2022-04-07 20:54:40.028249,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
20,599a1ebb-d8cf-4b22-8ce0-78b0e75646fe,sp::599a1ebb-d8cf-4b22-8ce0-78b0e75646fe,pay_mmsvbl7hqalexc4d4zxyqhvxay,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,500.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,b097e177-bea2-4513-b732-5d66dc4a0514,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-08 13:12:15.817,2022-04-08 13:12:22.033143,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
21,3546221e-1e83-4875-9426-b111943180cd,sp::3546221e-1e83-4875-9426-b111943180cd,pay_wittl74tr67urhspek3as7f37e,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,250.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,6f189b22-5b10-40e3-b1bd-5260c02e01ab,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-08 13:13:49.198,2022-04-08 13:13:53.959527,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
22,1169e8ed-a342-43f0-924d-ffbc5dcd99ba,sp::1169e8ed-a342-43f0-924d-ffbc5dcd99ba,pay_2xxasfqioaeune5to7mdiqbz2e,1b63a38f-c619-443c-bc97-121eb4d657d2,CARDPROVIDER,PLAMEN STEFANOV,PAYMENT_CARD,None,57.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,89be6652-6adf-43ad-af68-3adf485295b6,bananastefanov@gmail.com,STRIPE,Aytos,,BG,8500,None,2022-04-09 12:16:36.222,2022-04-09 12:17:34.130793,"{'card': {'bin': '440255', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
23,d71af0c5-6968-4148-97a1-70dd9a7d4bba,sp::d71af0c5-6968-4148-97a1-70dd9a7d4bba,pay_qpjfgw2s6uke7bqkwmxu4tymcu,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,500.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,5e8dc873-e02f-46b6-bccb-be5420c66d89,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-09 14:38:44.720,2022-04-09 14:38:51.481196,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
24,c2280611-c854-4ee6-b5d6-e03566e2ec1e,sp::c2280611-c854-4ee6-b5d6-e03566e2ec1e,pay_by6sok5hg72efjwzeuy7wzdobi,6767ea9a-57a9-4b4e-a603-ec986c813ccc,CARDPROVIDER,Gerald Faulkner,PAYMENT_CARD,None,500.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,97ef5bd4-dd0a-4de1-99f9-f69f96f4f207,gwfaulkner1@gmail.com,None,Pahrump,US-NV,US,89048,None,2022-04-09 14:41:50.792,2022-04-09 14:41:59.891060,"{'card': {'bin': '550780', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
25,cce27a09-7655-4826-ae56-1754cb060eff,sp::cce27a09-7655-4826-ae56-1754cb060eff,pay_cka67oxo64yufbkzmqzyq5xey4,832df285-10f7-4758-abab-50f994fb1d86,CARDPROVIDER,James Flores,PAYMENT_CARD,None,100.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,781c9a2f-9430-4ada-90e2-2527c08ce6d9,j3m4s@hotmail.com,None,Fresno,CA,US,93728,None,2022-04-10 14:13:06.097,2022-04-10 14:13:38.963858,"{'card': {'bin': '510805', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
26,94a0232d-8e83-4d18-8880-aebbdfadfce0,sp::94a0232d-8e83-4d18-8880-aebbdfadfce0,pay_ucuyta4eesoevasueddzza6v3u,832df285-10f7-4758-abab-50f994fb1d86,CARDPROVIDER,James Flores,PAYMENT_CARD,None,105.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,22396cd8-ca58-406a-97f4-161376fa89b8,j3m4s@hotmail.com,None,Fresno,CA,US,93728,None,2022-04-11 12:15:45.990,2022-04-11 12:16:17.547573,"{'card': {'bin': '510805', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
27,4511f818-edbe-40d9-a71f-3a2a007fe478,sp::4511f818-edbe-40d9-a71f-3a2a007fe478,pay_fxyurjrjeghe5lks4opbbprkiy,832df285-10f7-4758-abab-50f994fb1d86,CARDPROVIDER,James Flores,PAYMENT_CARD,None,115.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,a8df7201-2d88-4818-95be-871c45058cce,j3m4s@hotmail.com,None,Fresno,CA,US,93728,None,2022-04-11 14:14:20.914,2022-04-11 14:14:53.160400,"{'card': {'bin': '510805', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
28,4390db5e-9250-4e01-af35-125053961cc9,sp::4390db5e-9250-4e01-af35-125053961cc9,pay_bp6bjmixwosufbaurmvkfoxx44,b119286d-9fa7-4c1e-a5d2-fabf1ccb680e,CARDPROVIDER,Andrew Long,PAYMENT_CARD,None,100.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,c05a13b9-0002-4d75-a96f-8aff2b332550,andrewlong.bp@gmail.com,CHECKOUTDOTCOM,Tulsa,US-OK,US,74103,None,2022-04-11 17:11:53.581,2022-04-11 17:12:04.871391,"{'card': {'bin': '510625', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
29,7bed6872-3160-4280-ab22-676e41934dcc,sp::7bed6872-3160-4280-ab22-676e41934dcc,pay_zliuca5h35vuriow7ceepjsrey,e7434dde-d626-4682-bbcd-7ba782561f3e,CARDPROVIDER,ALEXANDRE S GOMEZ,PAYMENT_CARD,None,5.445000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,abf83e7a-c399-4551-a653-4c47c9eb6ffc,alex.sauri@gmail.com,STRIPE,Hostalric,,ES,17450,None,2022-04-12 12:52:11.605,2022-04-12 12:52:40.192429,"{'card': {'bin': '416598', 'type': 'visa', 'ye...","{'debit': 'PENDING_DEPOSIT', 'amount': {'EUR':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
30,42a8aed0-57d4-41ed-93b2-4168fc9fbb25,sp::42a8aed0-57d4-41ed-93b2-4168fc9fbb25,pay_wmhd2o6e6nvunmlqet4k7rzuc4,0ea7a2b7-80fd-440a-8e5f-5b2f0a6ff264,CARDPROVIDER,Jose Antonio González,PAYMENT_CARD,None,5.430000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,866d1d2f-cb65-4f15-9102-936caf102894,joseinformatica59@gmail.com,CHECKOUTDOTCOM,Ceuta,,ES,51002,None,2022-04-12 10:57:21.712,2022-04-12 10:57:43.863143,"{'card': {'bin': '548913', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'EUR':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
31,d9f63ca1-077e-44db-a8d8-ddd120dbf562,sp::d9f63ca1-077e-44db-a8d8-ddd120dbf562,pay_pebgzxoovgzeraucvvdbn5a7me,ae929756-d837-47d9-bd3a-0042473506da,CARDPROVIDER,Valet Thomas,PAYMENT_CARD,None,325.800000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,8e93fb0a-442e-481e-8120-b080deeb109f,y0dzerka@gmail.com,None,Aubencheul-au-Bac,Nord-Pas-de-Calais,FR,59265,None,2022-04-12 11:12:18.049,2022-04-12 11:12:45.091258,"{'card': {'bin': '535584', 'type': 'MASTERCARD...","{'debit': 'PENDING_DEPOSIT', 'amount': {'EUR':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
32,f6775d06-d2a7-42a8-8589-e8b90f7b7acd,sp::f6775d06-d2a7-42a8-8589-e8b90f7b7acd,pay_bvnybm5cqmyehaf2uhko3mgnve,f5b8adf0-4a48-494d-be54-5e650ed85e3a,CARDPROVIDER,Osniel Perez Zamora,PAYMENT_CARD,None,5.000000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,f769889e-9fa9-41b4-ae51-98c6c025eeb5,juancarlospbt@gmail.com,STRIPE,Ciudad de Mexico,,MX,03810,None,2022-04-13 07:42:47.071,2022-04-13 07:43:52.240833,"{'card': {'bin': '526777', 'type': 'mastercard...","{'debit': 'PENDING_DEPOSIT', 'amount': {'USD':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
33,1399e61b-68a5-4d84-bca5-468e0145a17d,sp::1399e61b-68a5-4d84-bca5-468e0145a17d,pay_4zc6zin7vf3e5hytybmhmt5jx4,adbe76e5-4764-4656-848d-67db60e08014,CARDPROVIDER,,PAYMENT_CARD,apple_pay,9.159800000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,ab116ea2-ac94-43cc-b593-92b6e36da495,andreemichaelis@web.de,CHECKOUTDOTCOM,Berlin,,DE,13355,None,2022-04-13 08:59:29.725,2022-04-13 09:38:42.333747,"{'name': '', 'type': 'PAYMENT_CARD', 'email': ...","{'debit': 'PENDING_DEPOSIT', 'amount': {'EUR':...","{'isMit': False, 'userTier': '2', 'cardProvide..."
34,0688b11b-21d4-4c1b-b0c0-fb617cb7b6e4,sp::0688b11b-21d4-4c1b-b0c0-fb617cb7b6e4,pay_dmu45lphtmkexba7mkcpcx6464,adbe76e5-4764-4656-848d-67db60e08014,CARDPROVIDER,,PAYMENT_CARD,apple_pay,8.664000000,COMPLETE,PENDING_DEPOSIT,SIMPLEBUY_BALANCE,False,2,2b39089c-4688-4f77-82af-86ad028b7a02,andreemichaelis@web.de,CHECKOUTDOTCOM,Berlin,,DE,13355,None,2022-04-13 09:53:28.699,2022-04-13 09:53:30.577560,"{'name': '', 'type': 'PAYMENT_CARD', 'email': ...","{'debit': 'PENDING_DEPOSIT', 'amount': {'EUR':...","{'isMit': False, 'userTier': '2', 'cardProvide..."